remote_theme: vanjac/theme
defaults:
  -
    scope:
      path: ""
    values:
      links:
        -
          title: Warehouse
          url: https://extensions.sketchup.com/user/extensions/5eb54850-2587-4a13-b5e2-0b270a7cecdb/Jacob%20van't%20Hoog
        -
          title: GitHub
          url: https://github.com/vanjac/su-extensions/
